//! General-purpose utilities
pub mod any;
pub mod borrow;
pub mod distributions;
pub mod fmt;
pub mod iter;
pub mod num_array;
pub mod order;
pub mod sequence;
pub mod slice;
pub mod stats;
pub mod vector;
